export const COMPANY_DOMAINS: Record<string, string> = {
  "Adobe": "adobe.com",
  "Airbnb": "airbnb.com",
  "Amazon": "amazon.com",
  "American Express": "americanexpress.com",
  "Apple Inc.": "apple.com",
  "Best Buy": "bestbuy.com",
  "Boeing": "boeing.com",
  "Chevron": "chevron.com",
  "Coca-Cola": "coca-cola.com",
  "Costco": "costco.com",
  "CVS Health": "cvshealth.com",
  "Delta Air Lines": "delta.com",
  "Disney": "disney.com",
  "DoorDash": "doordash.com",
  "Ford": "ford.com",
  "General Electric": "ge.com",
  "Google": "google.com",
  "Home Depot": "homedepot.com",
  "IBM": "ibm.com",
  "Intel": "intel.com",
  "Johnson & Johnson": "jnj.com",
  "JP Morgan": "jpmorganchase.com",
  "Kroger": "kroger.com",
  "Lockheed Martin": "lockheedmartin.com",
  "Lowe's": "lowes.com",
  "McDonald's": "mcdonalds.com",
  "Meta": "meta.com",
  "Microsoft": "microsoft.com",
  "Netflix": "netflix.com",
  "Nike": "nike.com",
  "Nvidia": "nvidia.com",
  "Oracle": "oracle.com",
  "PayPal": "paypal.com",
  "PepsiCo": "pepsico.com",
  "Pfizer": "pfizer.com",
  "Procter & Gamble": "pg.com",
  "Salesforce": "salesforce.com",
  "Samsung": "samsung.com",
  "Shell": "shell.com",
  "Sony": "sony.com",
  "Spotify": "spotify.com",
  "Starbucks": "starbucks.com",
  "T-Mobile": "t-mobile.com",
  "Target": "target.com",
  "Tesla": "tesla.com",
  "Toyota": "toyota.com",
  "Uber": "uber.com",
  "Uber Eats": "ubereats.com",
  "UPS": "ups.com",
  "Verizon": "verizon.com",
  "Visa": "visa.com",
  "Walmart": "walmart.com",
  "Walt Disney": "disney.com",
  "Wells Fargo": "wellsfargo.com",
  "Whirlpool": "whirlpool.com",
  "Xerox": "xerox.com",
};

export function companyLogoUrl(name: string): string | null {
  const domain = COMPANY_DOMAINS[name];
  if (!domain) return null;
  return `https://logo.clearbit.com/${domain}`;
}
